/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
 id("plugin.greeting") version("0.1.0")
}

import org.gradle.internal.classloader.ClasspathUtil;

tasks.register("classpath") {
    doLast {
        ClasspathUtil.getClasspath(plugin.PluginPlugin::class.java.getClassLoader()).getAsURLs().forEach {
            System.err.println(it);
        }
    }
}
